### ISSUE TITLE
Fantastic work!

### ISSUE THREAD

**Issue by it33** [LPgenerator/mattermost_bot#1]
Thanks so much making this! Would you be interested in [sharing more info about your work?](https://spinpunch.wufoo.com/forms/mattermost-integrations-and-installers/) Mattermost team would love to let the community know about it.

**Comment by gotlium** [comment]
Thank you too:) And for Mattermost team. I sent the form:)

**Comment by it33** [comment]
Perfect! Plan to list this week and tweet in next two weeks depending on what else is queued, thanks!
