### ISSUE TITLE
Make bot only respond to whispers

### ISSUE THREAD

**Issue by Grokzen** [LPgenerator/mattermost_bot#15]
Hi. Is there a way to make a bot only respond to direct whispers and make it respond back to the user that sent the message? There are some bots that could use this feature where it would not clog up a channel with alot of messages and output and limit output to only the user that really needs to see the information it would return.

**Comment by gotlium** [comment]
Hi, you can create your own decorator to do it. For example:

    from mattermost_bot.utils import allow_only_direct_message

    @respond_to('^selfupdate$')
    @allow_only_direct_message()   # allow only direct messages
    @admin_access_required()        # your own decorator, to limit users
    def self_update(message):
         ...


or you mean anything else?

**Comment by Grokzen** [comment]
Yes it sounds like something i am looking for.

**Comment by gotlium** [comment]
Could I close issue?

**Comment by Grokzen** [comment]
I will play with it tomorrow at work and see how it works.
