### ISSUE TITLE
SSL_Verify false doesn't work

### ISSUE THREAD

**Issue by tsmori** [LPgenerator/mattermost_bot#18]
I don't see anywhere in the code where the SSL_VERIFY variable is used and since python requests defaults to true, there isn't anyway to disable the verification.

**Comment by gotlium** [comment]
as argument here: https://github.com/LPgenerator/mattermost_bot/blob/master/mattermost_bot/bot.py#L27

as settings here:  https://github.com/LPgenerator/mattermost_bot/blob/master/mattermost_bot/settings.py#L16

rewriting here: https://github.com/LPgenerator/mattermost_bot/blob/master/mattermost_bot/settings.py#L36

`MATTERMOST_BOT_SSL_VERIFY=False` - environment variable will be disable ssl verification
or on settings
`SSL_VERIFY = False`

@pschmitt can explain more information about ssl verification

**Comment by pauvos** [comment]
Can confirm that environment variable MATTERMOST_BOT_SSL_VERIFY=False does not disable SSL verification.

```
[07/12/2016 12:24:08] Starting new HTTPS connection (1): team.chefkoch.net
[...]
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by tsmori** [comment]
I discovered that the pip install didn't get all the latest bits of the
project. The mattermost.py and bot.py files didn't have the SSL components.
I grabbed all the latest files and the SSL_VERIFY in the settings.py file
do work now.

Tim

**Comment by gotlium** [comment]
Version with ssl verification was released to PyPi.
