### ISSUE TITLE
Do you know this error?

### ISSUE THREAD

**Issue by doriri** [LPgenerator/mattermost_bot#2]
Traceback (most recent call last):
  File "run.py", line 25, in <module>
    main()
  File "run.py", line 20, in main
    bot = Bot()
  File "/home/doriri/mattermost_bot-master/mattermost_bot/bot.py", line 26, in __init__
    settings.BOT_LOGIN, settings.BOT_PASSWORD,
  File "/home/doriri/mattermost_bot-master/mattermost_bot/mattermost.py", line 96, in __init__
    self.login(team, email, password)
  File "/home/doriri/mattermost_bot-master/mattermost_bot/mattermost.py", line 100, in login
    self.user = self.api.login(team, email, password)
  File "/home/doriri/mattermost_bot-master/mattermost_bot/mattermost.py", line 44, in login
    self.token = p.headers["Token"]
  File "/usr/lib/python2.7/dist-packages/requests/structures.py", line 77, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'token'

**Comment by gotlium** [comment]
Yes, bot can not login and can not get token

**Comment by doriri** [comment]
Sorry, i mistake to question
i installing bot in Ubuntu 14.04.3 LTS
and command 'pip install mattermost_bot',
URL, Email, Pw, Team setting in settings.py
after, 'python run.py' but token error.

Do you know how to solve the problem?

**Comment by gotlium** [comment]
you are use `http://`mm.example.com`/api/v1` in BOT_URL?
or you can dump info 
https://github.com/LPgenerator/mattermost_bot/blob/master/mattermost_bot/mattermost.py#L43
add `print(p.text)`

**Comment by doriri** [comment]
i using "http://chat.architectgroup.com" in BOT_URL, its right?
and team "ArchitectGroup" in BOT_TEAM
dump message is 

<body class="white error">
	<div class="container-fluid">
		<div class="error__container">
			<div class="error__icon"><i class="fa fa-exclamation-triangle"></i></div>
			<h2>Finger Chat needs your help:</h2>
			<p>Sorry, we could not find the page.</p>
			<a href="http://chat.architectgroup.com/users">Go back to team site</a>
		</div>
	</div>
</body>
<script>
	var details = "

http://chat.architectgroup.com/users is real page but "we could not find the page" :(

**Comment by gotlium** [comment]
You should use `http://chat.architectgroup.com/api/v1` in BOT_URL

**Comment by doriri** [comment]
I'm sorry for late response

Thank you for sending me your kind reply, bot is run very well !!

**Comment by gotlium** [comment]
np)
