### ISSUE TITLE
Not working on Mattermost v3.3

### ISSUE THREAD

**Issue by tomedelliott** [LPgenerator/mattermost_bot#20]
I've just upgraded to [Mattermost 3.3](https://www.mattermost.org/mattermost-3-3-chinese-korean-dutch-message-flags-here-golang-bot-sample-and-much-more/), and my bot stopped working.

I think mattermost have made some changes to the API. "action" has changed to "event", so this [this line](https://github.com/LPgenerator/mattermost_bot/blob/master/mattermost_bot/mattermost.py#L165) needs changing accordingly.
Also json.loads is not fully loading all field correctly, on python 2.7.6.
 msg['data']['post'] is being returned as a string. Changing MessageDispatcher.get_message to this worked
```python
def get_message(msg):
    return json.loads(
        msg.get('data', {}).get('post', {})
    ).get('message', '').strip()
```
but is a bit hacky.

**Comment by tomedelliott** [comment]
Also looks like msg['props']['mentions'] is now msg['data']['mentions']

**Comment by gotlium** [comment]
thanks for your report. pls check new 1.0.18 for compatibility with v3.3

**Comment by tomedelliott** [comment]
Thanks for the update.

mattermost_bot 1.0.18 is working great now on mattermost v3.3

**Comment by gotlium** [comment]
good news)
