### ISSUE TITLE
Feature Request: Editable posts

### ISSUE THREAD

**Issue by thorlock12** [LPgenerator/mattermost_bot#21]
Hey, 

I'm looking at trying to edit a post with the bot, to do this we'd need to be able to get the id of a message sent originally. It's a previous message sent by the bot, but we would need the id of this. 

Currently message.send() returns none (no return statement at all), although the method it calls does return the message details but this isn't then returned. [here](https://github.com/LPgenerator/mattermost_bot/blob/master/mattermost_bot/dispatcher.py#L226)

Would also then need an update/edit method that posts channel_id, id(of the old message) and message to the following endpoint:
`http://youdomain.com/api/v3/teams/<team_id>/channels/<channel_id>/posts/update`

Seems easy enough on first thought, might make a pull request for this this weekend if I get the chance.

**Comment by gotlium** [comment]
Hi, it's a good idea)

**Comment by gotlium** [comment]
Thanks.
