### ISSUE TITLE
GitLab Login

### ISSUE THREAD

**Issue by ralgozino** [LPgenerator/mattermost_bot#24]
Hello there!

We are using mattermost toghether with GitLab CE, and we have disabled the email login. Is it possible to use GitLab login for a bot? If not, could you consider it?
Thanks!

**Comment by gotlium** [comment]
You can inspect login and write your own methods on api to perform actions.

**Comment by ralgozino** [comment]
I found a solution here:
https://forum.mattermost.org/t/solved-how-to-authenticate-bots-using-the-api/2405/2

Thanks.
