### ISSUE TITLE
Support custom settings module by enviornment variable

### ISSUE THREAD

**Issue by Grokzen** [LPgenerator/mattermost_bot#4]
Right now, the python settings file that we can create, must be importable as `mattermost_bot_settings` and that usually do not work so well when we package our bot custom code into a cli for example.

What would be great to change is to add the ability to specify a environment variable similar to how django can handle a custom settings file. Django has the `DJANGO_SETTINGS_MODULE=...` and this module could use for example `MATTERBOT_SETTINGS_MODULE=...` and it tries to import the `mattermost_bot_settings.py`  file inside that module.

**Comment by gotlium** [comment]
Good idea :+1:
