### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by ryuuji5** [LPgenerator/mattermost_bot#48]
Hello @gotlium,

I want to use mattermost_bot via LDAP authentication with Gitlab.
But, I have no idea...

How can I do this? mattermost_bot is not supported in this case??

Thank you.

**Comment by attzonko** [comment]
I am not 100% clear on what you are trying to do? Are you trying to have the bot account authenticate through LDAP? Currently I use LDAP authentication for my Mattermost instance, and still use mattermost_bot. What I did is created an account for the bot from the command line. Everyone else authenticates through LDAP.

**Comment by ryuuji5** [comment]
Yes, I am trying to have the bot account authenticate through LDAP and create websocket connection.
I could have gotten "MMAUTHTOKEN" and "Token" as response of posting HTTP request to [https://<gitlab-URL>/users/auth/ldapmain/callback].
But I can not get user information(json type) that can be gotten by posting HTTP request to [https://<mattermost-URL>/api/(v3 or v4)/users/login] with standard account without SSO.
