### ISSUE TITLE
Unicode messages in reply cause exception

### ISSUE THREAD

**Issue by Grokzen** [LPgenerator/mattermost_bot#6]
When i send a reply string with unicode characters (for example the swedish caracters åäö) i get the following exception.

```
Traceback (most recent call last):
  File "/home/grok/.virtualenvs/botdev/local/lib/python2.7/site-packages/mattermost_bot/dispatcher.py", line 66, in dispatch_msg
    func(Message(self._client, msg, self._pool), *args)
  File "/home/grok/code/fujitsu/matterbot/bot/cli.py", line 50, in quote_get
    message.reply(u"{}".format(data.get(str(id)), "No quote with ID: {0} exists in the database...".format(str(id))))
  File "/home/grok/.virtualenvs/botdev/local/lib/python2.7/site-packages/mattermost_bot/dispatcher.py", line 174, in reply
    self.send(self._gen_reply(text))
  File "/home/grok/.virtualenvs/botdev/local/lib/python2.7/site-packages/mattermost_bot/dispatcher.py", line 170, in _gen_reply
    return self._gen_at_message(text)
  File "/home/grok/.virtualenvs/botdev/local/lib/python2.7/site-packages/mattermost_bot/dispatcher.py", line 166, in _gen_at_message
    return '@{}: {}'.format(self.get_username(), text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 1: ordinal not in range(128)
```

The simplest solution i found was to change this line https://github.com/LPgenerator/mattermost_bot/blob/master/mattermost_bot/dispatcher.py#L166 to be the following: `return u'@{}: {}'.format(self.get_username(), text)` where the new string will be unicode.

**Comment by gotlium** [comment]
For Russian characters we are using following code

    return '@{}: {}'.format(self.get_username(), 'Привет')

**Comment by Grokzen** [comment]
If you are looking at the second line in the stacktrace above, you can see that we are using the message.reply method.

```
File "/home/grok/code/fujitsu/matterbot/bot/cli.py", line 50, in quote_get
    message.reply(u"{}".format(data.get(str(id)), "No quote with ID: {0} exists in the database...".format(str(id))))
```

and we are formatting the string we send into the bot layer with `u` to make it work with unicode. The quoted line above in dispatcher.py takes the string we gave it and formats it again but without unicode.

I am also abit confused, can you just return a string from the function that has the `@listen_to` or `@respond_to` decorator?

**Comment by gotlium** [comment]
What about compatibility with Python 3. You can test this method by your self and send pull request. I don't have a time at this moment. When I have more time, I can test this case. But give me all data for reproduce this problem.

**Comment by Grokzen** [comment]
I can test with python3 and see if there is any difference. Are you reccomending to run this lib in either python 2 or python 3, or are your intentions to support both versions at the same time?

**Comment by gotlium** [comment]
Yes, we are support both versions.

**Comment by Grokzen** [comment]
Sorted this out. It was the data that was read from a file that was the root cause of this problem. When that was fixed, it worked as expected.
