### ISSUE TITLE
BOT_URL

### ISSUE THREAD

**Issue by asadpiz** [LPgenerator/mattermost_bot#7]
Hi, What are the variables BOT_URL & BOT_TEAM supposed to contain?

Is BOT_URL, the URL to mattermost instance? or location of module "mattermost-bot"?

**Comment by gotlium** [comment]
example at #2 

   BOT_URL = 'http://chat.architectgroup.com/api/v1'
   BOT_TEAM = 'argp'

**Comment by asadpiz** [comment]
Thanks, I was ignoring http & api/v1 because that didn't make any sense for my URL. I have made a pull request for documentation that I think will be helpful for future users.
